FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["sh", "-c", "mkdir -p data/uploads && npx prisma generate && npx prisma db push && npm run dev -- --hostname 0.0.0.0 --port 3000"]
