export interface EquipmentItem {
  id: string;
  equipmentCode: string;
  name: string;
  type: string;
  category: string;
  model: string;
  serialNumber: string;
  inventoryNumber: string;
  department: string;
  location: string;
  status: "DRAFT" | "ACTIVE" | "INACTIVE" | "DECOMMISSIONED";
  lifecycleStage: "PLANNED" | "COMMISSIONED" | "IN_OPERATION" | "MAINTENANCE" | "RETIRED";
  criticality?: "A" | "B" | "C" | string;
  manufacturer?: string;
  supplier?: string;
  countryOfOrigin?: string;
  isImported?: boolean;
  isUnique?: boolean;
  productionDate?: string;
  deliveryDate?: string;
  commissioningDate?: string;
  responsibleUser?: string;
  warrantyExpiration?: string;
  serviceDueDate?: string;
  notes?: string;
  techSpecs?: Record<string, string>;
  version: number;
  updatedAt: string;
}
